In [4]:
import numpy as np
import pandas as pd
from model import NeuralNetwork
import time

In [5]:
train_data_raw = pd.read_csv('data/mnist_train.csv')
train_data_raw = train_data_raw.fillna(0)
train_data_raw = np.array(train_data_raw)
np.random.shuffle(train_data_raw)
train_data = train_data_raw[:,1:]
train_data = np.transpose(train_data/train_data.max())
train_labels = train_data_raw[:,0]


In [151]:
print(train_data.shape[1])
print(train_labels.shape)
print(train_labels)

59999
(59999,)
[9 9 6 ... 6 1 8]


In [116]:
train_labels = np.array([9])
print(train_labels)

[9]


In [192]:
print(np.max(train_labels)+1)

Y = np.zeros((int(np.max(train_labels)+1), int(train_labels.shape[0])))
print(Y.shape)
print(len(Y[0,:]))
print(Y.shape[1])
tic = time.perf_counter()
Y_loop = np.zeros((int(np.max(train_labels)+1), int(train_labels.shape[0])))
for i in range(Y.shape[1]):
    Y_loop[train_labels[i],i] = 1
toc = time.perf_counter()
print("bucle: ", toc-tic, "s")



tic = time.perf_counter()
Y_tensor = np.zeros((int(np.max(train_labels)+1), int(train_labels.shape[0])))
Y_tensor[train_labels, np.arange(train_labels.shape[0])] = 1
toc = time.perf_counter()
print("tensor: ", toc-tic, "s")

print(Y_loop == Y_tensor)

print(Y_tensor)


10
(10, 59999)
59999
59999
bucle:  0.021744609999586828 s
tensor:  0.0007573879993287846 s
[[ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 ...
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [1. 1. 0. ... 0. 0. 0.]]


In [ ]:
#inversed loop

m = 10
for i in range(m, 0, -1):
    print(i)


10
9
8
7
6
5
4
3
2
1


In [142]:
m = 10
for i in range(m+1, 20):
    print(i)

11
12
13
14
15
16
17
18
19


In [146]:
sizes = [128, 60, 50, 10]
for i in range(len(sizes), 0, -1):
    print(i)

4
3
2
1


In [147]:
a = 2**2
print(a)

4


In [160]:
print(Y_tensor[:,1:10])


[[0. 0. 0. 0. 0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [170]:
batch_size = 2048
batch_dim = train_data.shape[1] // batch_size
print(batch_dim)
for j in range(batch_dim):
    train_data_batch = train_data[:,int(j*batch_size):int((j+1)*batch_size)]
    train_data_label_batch = train_labels[int(j*batch_size):int((j+1)*batch_size)]
    print(train_data_label_batch)

train_data_batch = train_data[:,int(1*batch_size):int((2)*batch_size)]



29
[9 9 6 ... 2 9 4]
[6 0 5 ... 6 8 2]
[0 2 7 ... 2 5 4]
[6 1 5 ... 0 2 0]
[6 4 8 ... 1 1 3]
[9 2 8 ... 4 1 1]
[8 5 0 ... 8 4 7]
[0 6 1 ... 2 6 0]
[3 4 2 ... 3 4 7]
[4 8 3 ... 9 1 3]
[1 1 7 ... 3 3 8]
[6 1 4 ... 0 6 4]
[0 4 9 ... 3 6 7]
[8 8 0 ... 9 9 2]
[2 6 8 ... 5 1 1]
[7 2 1 ... 6 5 9]
[2 5 0 ... 1 5 7]
[9 1 3 ... 8 1 0]
[9 1 3 ... 6 7 1]
[1 3 4 ... 6 8 5]
[1 4 3 ... 2 3 7]
[8 2 8 ... 3 7 1]
[9 8 1 ... 9 8 0]
[9 8 6 ... 0 2 7]
[3 2 4 ... 4 5 5]
[7 5 0 ... 8 9 7]
[4 3 8 ... 3 1 3]
[1 1 6 ... 7 8 9]
[5 9 1 ... 0 0 8]


In [190]:
a = np.array(([1, 0, 0.5, 0.9], [0, 0, 1, 0]))
print(np.argmax(a, axis=0))

[0 0 1 0]


In [209]:
b = np.array((
    [10  ,10  ,0  ,0],
    [2  ,4  ,4  ,2],
    [7  ,5  ,10  ,3]
))

print(np.mean(b, axis=1))
print(np.mean(b, axis=1)[2])
print(np.arange(b.shape[0]))

for i in range(train_data.shape[0]):
    train_data[i,:] = np.mean(train_data, axis=1)[i]


print(train_data)

[5.   3.   6.25]
6.25
[0 1 2]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
print(train_data.shape)

batch_size = 1024
batch_dim = train_data.shape[1] // batch_size
for j in range(batch_dim):
    train_data_batch = train_data[:,int(j*batch_size):int((j+1)*batch_size)]
    train_labels_labels_batch = train_labels[int(j*batch_size):int((j+1)*batch_size)]
print(train_data_batch.shape)
print(train_data_label_batch)

(784, 59999)
(784, 1024)
