In [72]:
import numpy as np
import pandas as pd
from model import NeuralNetwork
import time

In [24]:
train_data_raw = pd.read_csv('data/mnist_train.csv')
train_data_raw = train_data_raw.fillna(0)
train_data_raw = np.array(train_data_raw)
np.random.shuffle(train_data_raw)
train_data = train_data_raw[:,1:]
train_data = np.transpose(train_data/train_data.max())
train_labels = train_data_raw[:,0]


In [50]:
print(train_data.shape)
print(train_labels.shape)
print(train_labels)

(784, 59999)
(59999,)
[3 5 6 ... 9 2 2]


In [75]:
train_labels = np.array([9, 1, 9, 3, 6, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 2, 9])
print(train_labels)

[9 1 9 3 6 5 6 7 8 9 0 1 2 3 4 5 6 7 2 9]


In [ ]:
print(np.max(train_labels)+1)

Y = np.zeros((int(np.max(train_labels)+1), int(train_labels.shape[0])))
print(Y.shape)
print(len(Y[0,:]))
print(Y.shape[1])
tic = time.perf_counter()
Y_loop = np.zeros((int(np.max(train_labels)+1), int(train_labels.shape[0])))
for i in range(Y.shape[1]):
    Y_loop[train_labels[i],i] = 1
toc = time.perf_counter()
print("bucle: ", toc-tic)

print(Y)

tic = time.perf_counter()
Y_tensor = np.zeros((int(np.max(train_labels)+1), int(train_labels.shape[0])))
Y[train_labels, np.arange(train_labels.shape[0])] = 1
toc = time.perf_counter()
print(Y)



10
(10, 20)
20
20
bucle:  0.0007142479989852291
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0